# Header

menu:
  主页: /
  分类: /categories/
  归档: /archives/



# SubNav
subnav:
  #qq: "619192323"
  #weixin: "qq619192323"
  github: "https://github.com/modestbean"
  csdn: "https://blog.csdn.net/ModestBean"
  #weibo: "#"
  zhihu: "https://www.zhihu.com/people/yin-dou-49/activities"
  jianshu: "https://www.jianshu.com/u/741a2009fb8e"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:yindou97@163.com"
  #rss: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
#show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '觉得对您有用，谢谢支持'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /images/shouzhi.jpg
# 微信二维码图片地址
weixin: /images/shou.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/tou.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false 

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
$disqus: false

# 注释所有畅言配置
# 注释所有gitalk配置
# livere配置
#livere: MTAyMC80NTI4Mi8yMTc5NQ==



#5、Gitment
# gitment_owner: modestbean      #你的 GitHub ID
# gitment_repo: 'modestbean.github.io'          #存储评论的 repo
# gitment_oauth:
#   client_id: 'c2691c7857c49fd25e5e'           #client ID
#   client_secret: 'b01629d6a585b5c72ac267fbb7efa5a7ddc6e4e3'       #client secret

#6、gitalk评论
gitalk:
  enable:  true
  githubID:  modestbean   
  repo:  'modestbean.github.io'
  ClientID:  'c2691c7857c49fd25e5e'
  ClientSecret:  'b01629d6a585b5c72ac267fbb7efa5a7ddc6e4e3'
  adminUser:  modestbean
  distractionFreeMode: true


# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: 'rgba(0,0,0,0)'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
  #左侧头像板块的背景颜色
  left_ground: 'url(/images/timg2.jpg)no-repeat 100%;background-size:cover;'


# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  CSDN: https://blog.csdn.net/ModestBean
  #友情链接2: http://localhost:4000/
  #友情链接3: http://localhost:4000/
  #友情链接4: http://localhost:4000/
  #友情链接5: http://localhost:4000/
  #友情链接6: http://localhost:4000/

aboutme: 计算机研究生，热爱图形学、图像处理领域。如何去处理问题比知识更重要，谢谢大家